name: Build

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  changes:
    runs-on: ubuntu-slim
    name: Check for Changes
    outputs:
      main: ${{ steps.filter.outputs.main }}
      events: ${{ steps.filter.outputs.events }}
      ws: ${{ steps.filter.outputs.ws }}
      stats: ${{ steps.filter.outputs.stats }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          base: ${{ github.ref }}
          filters: |
            main:
              - Dockerfile
              - src/**
              - package.json
              - bun.lock
            events:
              - Dockerfile.events
              - src/sharded/event-handler.ts
              - src/**
              - package.json
              - bun.lock
            ws:
              - Dockerfile.ws
              - src/sharded/discord-ws.ts
              - src/utils/initial-presence.ts
              # - package.json
              # - bun.lock
              # (if there is a meaningfull change to @discordjs/ws i'll manually trigger a build)
            stats:
              - Dockerfile.stats
              - src/sharded/stats-api.ts
              - src/utils/db.ts

  docker-build:
    name: Build Docker (${{ matrix.platform_suffix }})
    runs-on: ${{ matrix.runner }}
    needs: changes
    if: github.ref == 'refs/heads/main' && (needs.changes.outputs.main == 'true' || needs.changes.outputs.events == 'true' || needs.changes.outputs.ws == 'true' || needs.changes.outputs.stats == 'true' || github.event_name == 'workflow_dispatch')
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            platform: linux/amd64
            platform_suffix: x64
          - runner: ubuntu-24.04-arm
            platform: linux/arm64
            platform_suffix: arm64
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Prepare lowercase owner
        run: |
          echo "OWNER_LOWER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "[Main Image] Build & push image"
        uses: docker/build-push-action@v6
        if: ${{ needs.changes.outputs.main == 'true' || github.event_name == 'workflow_dispatch' }}
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LOWER }}/honeypot:${{ env.SHORT_SHA }}-${{ matrix.platform_suffix }}
          build-args: |
            GIT_SHA=${{ github.sha }}
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
      - name: "[Events Image] Build & push image"
        uses: docker/build-push-action@v6
        if: ${{ needs.changes.outputs.events == 'true' || github.event_name == 'workflow_dispatch' }}
        with:
          context: .
          file: ./Dockerfile.events
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LOWER }}/honeypot-events:${{ env.SHORT_SHA }}-${{ matrix.platform_suffix }}
          build-args: |
            GIT_SHA=${{ github.sha }}
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
      - name: "[ws Image] Build & push image"
        uses: docker/build-push-action@v6
        if: ${{ needs.changes.outputs.ws == 'true' || github.event_name == 'workflow_dispatch' }}
        with:
          context: .
          file: ./Dockerfile.ws
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LOWER }}/honeypot-ws:${{ env.SHORT_SHA }}-${{ matrix.platform_suffix }}
          build-args: |
            GIT_SHA=${{ github.sha }}
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
      - name: "[stats Image] Build & push image"
        uses: docker/build-push-action@v6
        if: ${{ needs.changes.outputs.stats == 'true' || github.event_name == 'workflow_dispatch' }}
        with:
          context: .
          file: ./Dockerfile.stats
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LOWER }}/honeypot-stats:${{ env.SHORT_SHA }}-${{ matrix.platform_suffix }}
          build-args: |
            GIT_SHA=${{ github.sha }}
          # cache-from: type=gha
          # cache-to: type=gha,mode=max

  merge-docker-manifest:
    name: Deploy Docker
    runs-on: ubuntu-latest
    needs: 
      - docker-build
      - changes
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Create and Push All Multi-arch Manifests"
        run: |
          SHORT_SHA="${GITHUB_SHA::7}"
          OWNER_LOWER="${GITHUB_REPOSITORY_OWNER,,}"

          if [ "${{ needs.changes.outputs.main }}" = 'true' ] || [ "${{ github.event_name }}" = 'workflow_dispatch' ]; then
          docker buildx imagetools create \
            -t ghcr.io/$OWNER_LOWER/honeypot:$SHORT_SHA \
            -t ghcr.io/$OWNER_LOWER/honeypot:latest \
            ghcr.io/$OWNER_LOWER/honeypot:${SHORT_SHA}-x64 \
            ghcr.io/$OWNER_LOWER/honeypot:${SHORT_SHA}-arm64
          fi

          if [ "${{ needs.changes.outputs.events }}" = 'true' ] || [ "${{ github.event_name }}" = 'workflow_dispatch' ]; then
          docker buildx imagetools create \
            -t ghcr.io/$OWNER_LOWER/honeypot-events:$SHORT_SHA \
            -t ghcr.io/$OWNER_LOWER/honeypot-events:latest \
            ghcr.io/$OWNER_LOWER/honeypot-events:${SHORT_SHA}-x64 \
            ghcr.io/$OWNER_LOWER/honeypot-events:${SHORT_SHA}-arm64
          fi

          if [ "${{ needs.changes.outputs.ws }}" = 'true' ] || [ "${{ github.event_name }}" = 'workflow_dispatch' ]; then
          docker buildx imagetools create \
            -t ghcr.io/$OWNER_LOWER/honeypot-ws:$SHORT_SHA \
            -t ghcr.io/$OWNER_LOWER/honeypot-ws:latest \
            ghcr.io/$OWNER_LOWER/honeypot-ws:${SHORT_SHA}-x64 \
            ghcr.io/$OWNER_LOWER/honeypot-ws:${SHORT_SHA}-arm64
          fi

          if [ "${{ needs.changes.outputs.stats }}" = 'true' ] || [ "${{ github.event_name }}" = 'workflow_dispatch' ]; then
          docker buildx imagetools create \
            -t ghcr.io/$OWNER_LOWER/honeypot-stats:$SHORT_SHA \
            -t ghcr.io/$OWNER_LOWER/honeypot-stats:latest \
            ghcr.io/$OWNER_LOWER/honeypot-stats:${SHORT_SHA}-x64 \
            ghcr.io/$OWNER_LOWER/honeypot-stats:${SHORT_SHA}-arm64
          fi
